source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'EGFormValidatorExample' do
    pod 'EGFormValidator', :git => 'https://github.com/alusev/EGFormValidator.git', :branch => 'master'
end
